module.exports = {
    getMeetings: "SELECT id,country, method,value,time,url,product_id,created_time FROM meeting ORDER BY created_time DESC",
    createMeeting: "INSERT INTO meeting(country,method,value,time,url,product_id,created_time) VALUES (?,?,?,?,?,?,?);",
    getProduct: "SELECT * FROM products WHERE id = ?;",
    getCategoryDetail: "SELECT * FROM category WHERE id = ?;",
    getNavDetail: "SELECT * FROM nav WHERE id = ?;",
    getBanners: "SELECT * FROM banners;",
    findUser: "SELECT * FROM user WHERE email = ?;",
    findCategory: "SELECT * FROM category WHERE name = ?;",
    findNav: "SELECT * FROM nav WHERE name = ?;",
    deleteCategory: "DELETE FROM category WHERE id = ?;",
    deleteProduct: "DELETE FROM products WHERE id = ?;",
    validUser: "select username,password from user WHERE username = ? and password = ?;",
    registUser: "INSERT INTO user(username,email,password) VALUES (?,?,?);",
    createProduct: "INSERT INTO products(name,stock_level,img_list,sku,create_time,category,description,user,base_price,sale_price,type) VALUES (?,?,?,?,?,?,?,?,?,?,?);",
    createCategory: "INSERT INTO category(name,create_time,update_time,description,img) VALUES (?,?,?,?,?);",
    createNav: "INSERT INTO nav(name,url,created_time,description) VALUES (?,?,?,?);",
    updateProduct: "UPDATE products SET name = ? , stock_level = ? , img_list = ? , sku = ? , category = ? , description = ? , base_price = ? , sale_price = ?, update_time = ? WHERE id = ?;",
    updateCategory: "UPDATE category SET name = ? , create_time = ? , update_time = ? , description = ? , url = ? WHERE id = ?;",
    updateNav: "UPDATE nav SET name = ? , create_time = ? , update_time = ? , description = ? , img = ? WHERE id = ?;",
    updateUser: "UPDATE user SET username = ? , password = ? , avatar = ?  WHERE id = ?;",
    findProduct: "SELECT * FROM products WHERE sku LIKE ? OR id LIKE ? OR name LIKE ?;",
}